---
title: Sam Warnick
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Sam Warnick
author: Sam Warnick
description: The personal blog of Sam Warnick
url: https://samwarnick.com
logo: "/assets/img/profile_inset@3x.png"
twitter:
  username: samwarnick
social:
  name: Sam Warnick
  links:
  - https://twitter.com/samwarnick
  - https://www.linkedin.com/in/samwarnick
  - https://github.com/samwarnick
  - https://keybase.io/samwarnick
markdown: kramdown
permalink: "/:year/:month/:title"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-gist
include:
- ".well-known"
