[[headers]]
for = "/assets/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31526000"

[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = [".cache"]

[images]
remote_images = ["https://blog.warnick.me/.*"]

[build.environment]
TZ = 'America/New_York'

[[redirects]]
from = "/media/*"
to = "/.netlify/images?url=https://blog.warnick.me/:splat&fm=webp&q=90"
status = 200
