[[headers]]
for = "/assets/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31526000"

[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = [".cache"]

[images]
remote_images = ["https://blog.warnick.me/.*", "https://images.pokemontcg.io/.*"]

[build.environment]
TZ = 'America/New_York'

[[redirects]]
from = "/media/og/*"
to = "/.netlify/images?url=https://blog.warnick.me/:splat&fm=jpg&w=1200&h=630&fit=cover"
status = 200

[[redirects]]
from = "/media/*"
to = "/.netlify/images?url=https://blog.warnick.me/:splat&fm=webp&q=90"
status = 200

[[redirects]]
from = "/random"
to = "/.netlify/functions/random-post"
status = 200

[functions]
directory = "functions"
included_files = ["./_site/feed.json"]
