[[headers]]
for = "/assets/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31526000"

[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = [".cache", "_site/og-images"]

[[plugins]]
package = "netlify-plugin-debug-cache"

[images]
remote_images = ["https://media.samwarnick.com/.*", "https://images.pokemontcg.io/.*", "https://books.google.com/.*"]

[build.environment]
TZ = 'America/New_York'

[[redirects]]
from = "/media/og/*"
to = "/.netlify/images?url=https://media.samwarnick.com/:splat&fm=jpg&w=1200&h=630&fit=cover"
status = 200

[[redirects]]
from = "/media/video/*"
to = "https://media.samwarnick.com/:splat"
status = 200

[[redirects]]
from = "/media/*"
to = "/.netlify/images?url=https://media.samwarnick.com/:splat&fm=webp&q=90"
status = 200

[[redirects]]
from = "/feed.rss"
to = "/rss.xml"
status = 301

[[redirects]]
from = "/styleguide"
to = "/site/#styleguide"
status = 302
