[phases.install]
cmds = ["npm ci"]

[phases.build]
cacheDirectories = ["/cache/og-images"]
cmds = [
    "mkdir -p /cache/og-images _site/og-images",
    "cp -r /cache/og-images/* _site/og-images/ 2>/dev/null || true",
    "npx @11ty/eleventy",
    "cp -r _site/og-images/* /cache/og-images/"
]