name: "Publish"
on:
  schedule:
    - cron: "30 14 * * *"

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} {{ NETLIFY_HOOK }}
