name: "Publish"
on:
  schedule:
    - cron: "30 14 * * *"

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6686d5d5c0f65546a50e72f8
