name: "Publish"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          NETLIFY_HOOK: ${{ secrets.NETLIFY_HOOK }}
        run: curl -X POST -d {} $NETLIFY_HOOK
